---
# https://taskfile.dev
version: "3"

tasks:
  init:
    desc: Install some important commands and tools
    cmds:
  assets:
    desc: Build the assets
    cmds:
      - npx tailwindcss -i ./internal/assets/tailwind.css -o ./internal/assets/dist/styles.css
      - tsc -build
  generate:
    desc: Generate stuff and things
    cmds:
      - go generate ./...
  run:
    desc: Run the application
    deps:
      - assets
      - generate
    cmds:
      - cd cmd/server && air
  test:
    desc: Run the tests
    cmds:
      - go test ./...
